---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library("p8105.datasets")
library(plotly)
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>% # let dataset smaller
  select(neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>% 
  filter(
    neighbourhood_group == "Manhattan",
    price  %in% 100:500,
    room_type == "Entire home/apt"
  ) %>% 
  drop_na(rating)
```



Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
nyc_airbnb %>% 
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) %>% # "\n": new line
  plot_ly(
    x = ~lat, y = ~long, color = ~price, text = ~text_label, # add text label on the graph
    alpha = 0.5, type = "scatter", mode = "markers")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% #reorder `neighbourhood` based on `price`
  plot_ly(x = ~neighbourhood, y = ~price, color = ~neighbourhood,
          type = "box", colors = "viridis")
```

### Chart C

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% #how many in each `neighbourhood`
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood,
          type = "bar", colors = "viridis")
```

